logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug
spring:
  h2:
    console:
      enabled: true
  profiles:
    active: local
handlebars:
  suffix: .html
